// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXgXbU-67MyjO3WfX2jTM2boG_QtGAf8g',
    appId: '1:501429312352:web:78ab6a30e706b65b6ddc05',
    messagingSenderId: '501429312352',
    projectId: 'myproject-a52ae',
    authDomain: 'myproject-a52ae.firebaseapp.com',
    storageBucket: 'myproject-a52ae.firebasestorage.app',
    measurementId: 'G-SQ8W3GDEPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkkliM5bVlsH_c0SfP-yMeiyDO18IhfA',
    appId: '1:501429312352:android:93db42d7962d8d906ddc05',
    messagingSenderId: '501429312352',
    projectId: 'myproject-a52ae',
    storageBucket: 'myproject-a52ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAyvcpLRoygbpTGuIVazG7QSlj7sANZ6A',
    appId: '1:501429312352:ios:e28198c8c0b90edc6ddc05',
    messagingSenderId: '501429312352',
    projectId: 'myproject-a52ae',
    storageBucket: 'myproject-a52ae.firebasestorage.app',
    iosBundleId: 'com.example.myECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAyvcpLRoygbpTGuIVazG7QSlj7sANZ6A',
    appId: '1:501429312352:ios:e28198c8c0b90edc6ddc05',
    messagingSenderId: '501429312352',
    projectId: 'myproject-a52ae',
    storageBucket: 'myproject-a52ae.firebasestorage.app',
    iosBundleId: 'com.example.myECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXgXbU-67MyjO3WfX2jTM2boG_QtGAf8g',
    appId: '1:501429312352:web:ce73151b63a733876ddc05',
    messagingSenderId: '501429312352',
    projectId: 'myproject-a52ae',
    authDomain: 'myproject-a52ae.firebaseapp.com',
    storageBucket: 'myproject-a52ae.firebasestorage.app',
    measurementId: 'G-7CX5Q8H1HP',
  );
}
